### ISSUE TITLE
Translateable error message

### ISSUE THREAD

**Issue by kevingerspacher** [mendixlabs/mendix-file-dropper#14]
We are currently using this widget in a Mendix project with German language. 
If a not supported file is uploaded the widget shows a popup with the english text "The following files are rejected: ...". 

Could you add a way where we can translate this string into another language without changing the source code of the widget?

**Comment by stephanbruijnis** [comment]
Currently the Dropzone, Maximum and Delete texts are properties of the widget. Texts that can be managed from the studio. 
Please add the error message for Rejected by Server (File: '"+e.name+"' rejected by the server") to this as well.

**Comment by JelteMX** [comment]
Fixed in [1.4.0](https://github.com/mendixlabs/mendix-file-dropper/releases/tag/1.4.0)
