### ISSUE TITLE
File dropper behavior

### ISSUE THREAD

**Issue by LItal1234** [mendixlabs/mendix-file-dropper#17]
I am using the file dropper widget and I have one issue and two requests.
Issue:
Page that contains two file droppers show the same text inside the drop zone. The text from bottom file dropper.
Is there a way to fix this?
Request:
Verification text of rejected file contains the file name and the name can not be removed. Is there a way to remove the name?
When deleting a file from the preview section there is no way to set an after commit microflow in order to update UI. Is there a way to get notice (After delete) deletion?

**Comment by RichKarona** [comment]
We are also seeing the 'same text' issue when multiple file droppers used on same page.

**Comment by JelteMX** [comment]
Issue was reported by multiple people eventually, if have fixed the issue in [1.4.0](https://github.com/mendixlabs/mendix-file-dropper/releases/tag/1.4.0).

The requests are partially implemented, added more translatable texts per #14. Regarding the deletion I didn't quite understand it, please file another issue if still needed, plus give a little bit more context
