### ISSUE TITLE
Not able to add a .msg file

### ISSUE THREAD

**Issue by wouterVijverberg** [mendixlabs/mendix-file-dropper#18]
I have used the file dropper widget in my Mendix projects and trying to allow dropping outlook messages as attachment to my project. It works for PDF, but for an outlook file (.msg) I get an error message. I already added the mime type to the restrictions list:
application/vnd.ms-outlook

The following files are rejected
mail.msg

Any clue how to solve this?

**Comment by JelteMX** [comment]
Unfortunately MIME types are spotty in browsers, it is best to handle this server side and somehow process the file in the backend, to see if you want to accept it or not. Closing the issue as this is rather old and has no follow-ups, plus not possible to fix in the widget itself
