### ISSUE TITLE
Images taken with camera do not show up

### ISSUE THREAD

**Issue by nenadTod** [mendixlabs/mendix-file-dropper#20]
Hello! 

First of all, thanks for this great widget!

We are planning to use it for our application, but we have a problem. 
On iOS, using Safari, there seems to be an issue with the widget when we use the camera as a source.
It allows us only to add one image by using the camera. If I try adding another one, in the same way, nothing happens.
The image just does not get shown, and it does not get sent to the server nor committed to the database.

Nothing shows up in the logs. I've tried debugging the application with after-create, after-commit events. The debugger does not trigger. I've also tried using the Validate Before microflow, and it does not get triggered either.

The version of Mendix that we used is 8.18.5.

Do you have any info about why this could be the case? When we try the same thing but use the gallery instead of the camera, everything works fine.

Best regards,
Nenad Todorović

**Comment by JelteMX** [comment]
Unfortunately this seems to be a browser issue, not an issue with the widget. I did update the react-dropzone component, this might help. If the problem persists, please reopen the issue
