### ISSUE TITLE
Error on file drop when Context/Association Object is not already committed

### ISSUE THREAD

**Issue by RichKarona** [mendixlabs/mendix-file-dropper#21]
If the file dropper is used to upload a file that needs to be associated with a context object, and the context object is not committed then the widget throws an error.

**Comment by JelteMX** [comment]
Problem is partially Mendix, partially the widget. The widget itself creates the file objects and tries to set an association to your context.

I have added a before commit Nanoflow/Microflow option in 'Events' that mitigates this, is released in [1.4.0](https://github.com/mendixlabs/mendix-file-dropper/releases/tag/1.4.0). You can find an example of this in the Home page of the [test-project](https://github.com/mendixlabs/widget-test-projects/raw/master/projects/filedropper/FileDropper.mpk)
