### ISSUE TITLE
Support prevention of continuation while uploading files.

### ISSUE THREAD

**Issue by Narev** [mendixlabs/mendix-file-dropper#25]
It would be nice if you could somehow prevent users from continuing when they are busy uploading files. You could achieve this by adding support for the queuecomplete event and the addedfile event. You could trigger a nf/mf to set the state of your context object to prevent clicking the next button or something like that. Ofcourse users can still browse away but this makes it more user friendly.

**Comment by JelteMX** [comment]
There is already an after commit microflow/nanoflow in 'Events' present. This is executed after every file upload, so this is already possible. There is also a before commit microflow/nanoflow, so you can even set this status before it upload files.

**Comment by Narev** [comment]
Thanks i will try and see how this will work. I suspect that this could give timing issues when you have a large upload and a small upload. e.g. if the small upload finishes it updates the context object while the large upload is still running. Or you would somehow need to add a counter to see how many files are being uploaded. But this could give you other problems. Anyway for now i will see how this will work out.
